export const PRESETS = {
  overlap: {
    mode: "normal",
    muNeg: 0,
    sdNeg: 1,
    muPos: 0.55,
    sdPos: 1,
    outlierFrac: 0,
    nPerClass: 500,
    samplePosFrac: 0.5,
    desc: "Expected ROC shape: close to diagonal baseline (high overlap).\nExpected PR shape: near the prevalence baseline with limited lift.\nE.g. weak-signal models where positives and negatives are hard to separate.",
  },
  separated: {
    mode: "normal",
    muNeg: 0,
    sdNeg: 1,
    muPos: 2.2,
    sdPos: 1,
    outlierFrac: 0,
    nPerClass: 500,
    samplePosFrac: 0.5,
    desc: "Expected ROC shape: pronounced top-left belly (good separation).\nExpected PR shape: high precision over a wide recall range.\nE.g. a strong model on a clean feature set.",
  },
  unequal: {
    mode: "normal",
    muNeg: 0,
    sdNeg: 0.8,
    muPos: 1.6,
    sdPos: 1.7,
    outlierFrac: 0,
    nPerClass: 600,
    samplePosFrac: 0.5,
    desc: "Expected ROC shape: asymmetric curvature from unequal variances.\nE.g. settings where one class is much more heterogeneous than the other.",
  },
  lognormal: {
    mode: "lognormal",
    muNeg: 0.0,
    sdNeg: 1.0,
    muPos: 1.0,
    sdPos: 1.0,
    outlierFrac: 0,
    nPerClass: 700,
    samplePosFrac: 0.5,
    logSigma: 0.7,
    desc: "Expected ROC shape: smooth but skew-driven bend (not symmetric like Gaussian).\nE.g. workflows with multiplicative effects or strongly right-skewed scores (long tail toward higher scores).",
  },
  heavytail: {
    mode: "student_t",
    muNeg: 0,
    sdNeg: 1,
    muPos: 1.45,
    sdPos: 1,
    outlierFrac: 0,
    nPerClass: 700,
    samplePosFrac: 0.5,
    dfNeg: 3,
    dfPos: 3,
    desc: "Expected ROC shape: flatter shoulders from heavy tails/outliers.\nE.g. domains with occasional extreme-score cases and outlier-prone inputs.",
  },
  mixture: {
    mode: "mixture_pos",
    muNeg: 0,
    sdNeg: 1,
    muPos: 2.3,
    sdPos: 0.9,
    outlierFrac: 0,
    nPerClass: 800,
    samplePosFrac: 0.5,
    mixWeight: 0.24,
    mixOffset: 0.15,
    mixSdMult: 1.1,
    desc: "Expected ROC shape: visible kink/shoulder from class heterogeneity.\nE.g. one class containing multiple sub-populations with different score behavior.",
  },
  zeroinflated: {
    mode: "zero_inflated",
    muNeg: -0.2,
    sdNeg: 0.9,
    muPos: 1.8,
    sdPos: 1.0,
    outlierFrac: 0,
    nPerClass: 900,
    samplePosFrac: 0.5,
    p0Neg: 0.42,
    p0Pos: 0.12,
    zeroValue: 0,
    desc: "Expected ROC shape: step-like segments from many tied zero scores.\nExpected PR shape: staircase-like segments from the same score ties.\nE.g. sparse-trigger systems where many cases receive the same floor score.",
  },
  uniform: {
    mode: "uniform",
    muNeg: 0.0,
    sdNeg: 1.0,
    muPos: 1.5,
    sdPos: 1.0,
    outlierFrac: 0,
    nPerClass: 700,
    samplePosFrac: 0.5,
    desc: "Expected shape: piecewise-linear style with gentler bends.",
  },
  exponential: {
    mode: "exponential",
    muNeg: -0.2,
    sdNeg: 0.9,
    muPos: 0.95,
    sdPos: 0.9,
    outlierFrac: 0,
    nPerClass: 700,
    samplePosFrac: 0.5,
    desc: "Expected ROC shape: skewed curvature from one-sided tails.",
  },
  probGoodSep: {
    mode: "beta",
    alphaNeg: 1.3,
    betaNeg: 10.5,
    alphaPos: 10.5,
    betaPos: 1.3,
    outlierFrac: 0,
    nPerClass: 700,
    samplePosFrac: 0.5,
    desc: "Probability-like scores in [0,1] with clear class separation.",
  },
  probOverlap: {
    mode: "beta",
    alphaNeg: 2.7,
    betaNeg: 4.1,
    alphaPos: 4.1,
    betaPos: 2.7,
    outlierFrac: 0,
    nPerClass: 700,
    samplePosFrac: 0.5,
    desc: "Probability-like scores in [0,1] with substantial overlap.\nE.g. early model iterations or inherently ambiguous tasks.",
  },
  probOverconfident: {
    mode: "beta",
    alphaNeg: 0.35,
    betaNeg: 3.5,
    alphaPos: 3.5,
    betaPos: 0.35,
    outlierFrac: 0,
    nPerClass: 700,
    samplePosFrac: 0.5,
    desc: "Probability-like scores in [0,1] with many near 0/1 and very sharp confidence.",
  },
  probMidrange: {
    mode: "beta",
    alphaNeg: 8.0,
    betaNeg: 12.0,
    alphaPos: 12.0,
    betaPos: 8.0,
    outlierFrac: 0,
    nPerClass: 700,
    samplePosFrac: 0.5,
    desc: "Probability-like scores concentrated in the middle, with moderate separability.",
  },
  probConfidentErrors: {
    mode: "beta_conf_mixture",
    epsPos: 0.12,
    epsNeg: 0.08,
    confSharpness: 14.0,
    outlierFrac: 0,
    nPerClass: 700,
    samplePosFrac: 0.5,
    desc: "Mostly high-confidence correct scores, with a minority of high-confidence mistakes on both classes.\nE.g. distribution shift, label noise, or shortcut learning that creates confident failures.",
  },
};
